// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXLp4fSzk-fri7FZKED7Cru2rQLmpXTk',
    appId: '1:477400149205:web:40a2b0f5b6ea85109f065c',
    messagingSenderId: '477400149205',
    projectId: 'social-sphere-6b4a2',
    authDomain: 'social-sphere-6b4a2.firebaseapp.com',
    storageBucket: 'social-sphere-6b4a2.firebasestorage.app',
    measurementId: 'G-516FBWBD5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEXa1PgdZoG7EViOxuO7nzij3jBExNPLY',
    appId: '1:477400149205:android:e88d992949ebd6799f065c',
    messagingSenderId: '477400149205',
    projectId: 'social-sphere-6b4a2',
    storageBucket: 'social-sphere-6b4a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1_b69e14STtDefO-TZTXQ8qFyW9eMJQ',
    appId: '1:477400149205:ios:f041f3f60f7934349f065c',
    messagingSenderId: '477400149205',
    projectId: 'social-sphere-6b4a2',
    storageBucket: 'social-sphere-6b4a2.firebasestorage.app',
    iosBundleId: 'com.example.socialSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1_b69e14STtDefO-TZTXQ8qFyW9eMJQ',
    appId: '1:477400149205:ios:f041f3f60f7934349f065c',
    messagingSenderId: '477400149205',
    projectId: 'social-sphere-6b4a2',
    storageBucket: 'social-sphere-6b4a2.firebasestorage.app',
    iosBundleId: 'com.example.socialSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeXLp4fSzk-fri7FZKED7Cru2rQLmpXTk',
    appId: '1:477400149205:web:0b77d869c07edb0f9f065c',
    messagingSenderId: '477400149205',
    projectId: 'social-sphere-6b4a2',
    authDomain: 'social-sphere-6b4a2.firebaseapp.com',
    storageBucket: 'social-sphere-6b4a2.firebasestorage.app',
    measurementId: 'G-4BT7552TNC',
  );
}
